"""
Django settings for provixa project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge les variables depuis un fichier .env local (non versionné) s'il existe.
# En production, définir ces variables directement dans l'environnement du serveur.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret !
# En local, la valeur ci-dessous sert de repli pratique. En production, définir
# IMPÉRATIVEMENT la variable d'environnement DJANGO_SECRET_KEY (une clé dédiée,
# jamais celle-ci qui a été exposée dans l'historique du projet).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    '-##ulnxewrz%f+40%pdt4mw9j@#sc8p-+zp*if_%g8*6*9ko(u',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Par défaut activé (confort de dev local) ; en production, définir
# DJANGO_DEBUG=false dans les variables d'environnement.
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    # En production : lister les domaines exacts via la variable d'environnement
    # DJANGO_ALLOWED_HOSTS (séparés par des virgules), ex: "provixa.ma,www.provixa.ma"
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'commercial',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'provixa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'provixa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Mode démo (ex: déploiement Render de démonstration) : base SQLite recréée et
# repeuplée avec des données factices à chaque démarrage du serveur (voir la
# commande `init_demo` et son appel dans le Start Command). Activé via la
# variable d'environnement DJANGO_MODE_DEMO=true ; en local, on garde la
# connexion SQL Server habituelle.
MODE_DEMO = os.environ.get('DJANGO_MODE_DEMO', 'false').lower() == 'true'

if MODE_DEMO:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db_demo.sqlite3',
        }
    }
    # Les migrations de l'app 'commercial' figent French_CI_AS (collation SQL
    # Server) dans leur état historique. On les désactive en mode démo : la
    # commande `init_demo` crée elle-même les tables non gérées, et
    # `migrate --run-syncdb` crée Signalement (seul modèle managed=True de
    # l'app) directement depuis l'état actuel des modèles, sans collation.
    MIGRATION_MODULES = {'commercial': None}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': 'Provixa',
            'HOST': '.\\SQLEXPRESS',  # ← Ajoute \SQLEXPRESS pour SQL Server Express
            'PORT': '',                        # ← Laisse vide (port 1433 par défaut)
            'USER': '',                        # ← Laisse vide si Trusted Connection
            'PASSWORD': '',                    # ← Laisse vide si Trusted Connection
            'OPTIONS': {
                'driver': 'ODBC Driver 17 for SQL Server',
                'Trusted_Connection': 'yes',   # ← Majuscule correcte
                'TrustServerCertificate': 'yes',
                'Connection Timeout': 30,      # ← Ajouter un timeout
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# ------------------------------------------------------------------
# Sécurité (cookies, HTTPS, sessions)
# Les protections HTTPS ne s'activent qu'en production (DEBUG=False) : les
# imposer en local casserait la connexion en http:// pendant le développement.
# ------------------------------------------------------------------

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Expire la session après 8h d'inactivité (durée glissante grâce à
# SESSION_SAVE_EVERY_REQUEST, pas juste 8h fixes depuis la connexion).
SESSION_COOKIE_AGE = 8 * 60 * 60
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
