# Generated by Django 6.0.8 on 2026-08-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id_agence', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('nom_agence', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, db_collation='French_CI_AS', max_length=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actif', models.BooleanField()),
            ],
            options={
                'db_table': 'Agence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(db_collation='French_CI_AS', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChefRegion',
            fields=[
                ('id_chef_region', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('nom_chef_region', models.CharField(db_collation='French_CI_AS', max_length=100)),
                ('prenom_chef_region', models.CharField(blank=True, db_collation='French_CI_AS', max_length=60, null=True)),
                ('telephone', models.CharField(blank=True, db_collation='French_CI_AS', max_length=30, null=True)),
                ('email', models.CharField(db_collation='French_CI_AS', max_length=200, unique=True)),
                ('date_prise_poste', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField()),
            ],
            options={
                'db_table': 'Chef_Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('prenom_client', models.CharField(blank=True, db_collation='French_CI_AS', max_length=100, null=True)),
                ('nom_client', models.CharField(db_collation='French_CI_AS', max_length=100)),
                ('ville', models.CharField(blank=True, db_collation='French_CI_AS', max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('code_categorie', models.CharField(blank=True, db_collation='French_CI_AS', max_length=30, null=True)),
                ('actif', models.BooleanField()),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id_commercial', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('nom_commercial', models.CharField(db_collation='French_CI_AS', max_length=100)),
                ('prenom_commercial', models.CharField(blank=True, db_collation='French_CI_AS', max_length=60, null=True)),
                ('telephone', models.CharField(blank=True, db_collation='French_CI_AS', max_length=30, null=True)),
                ('email', models.CharField(db_collation='French_CI_AS', max_length=200, unique=True)),
                ('date_prise_poste', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField()),
            ],
            options={
                'db_table': 'Commercial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id_ligne', models.AutoField(primary_key=True, serialize=False)),
                ('prix_unitaire', models.DecimalField(decimal_places=6, max_digits=10)),
                ('quantite', models.IntegerField()),
            ],
            options={
                'db_table': 'Ligne_vente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(db_collation='French_CI_AS', max_length=100, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, db_collation='French_CI_AS', max_length=500, null=True)),
                ('chemin_image', models.CharField(blank=True, db_collation='French_CI_AS', max_length=500, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField()),
            ],
            options={
                'db_table': 'Produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_region', models.CharField(db_collation='French_CI_AS', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typevendeur',
            fields=[
                ('id_type_vendeur', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_type_vendeur', models.CharField(db_collation='French_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'TypeVendeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id_vendeur', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('nom_vendeur', models.CharField(db_collation='French_CI_AS', max_length=100)),
                ('prenom_vendeur', models.CharField(blank=True, db_collation='French_CI_AS', max_length=60, null=True)),
                ('email', models.CharField(blank=True, db_collation='French_CI_AS', max_length=200, null=True, unique=True)),
                ('actif', models.BooleanField()),
            ],
            options={
                'db_table': 'Vendeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id_vente', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField()),
            ],
            options={
                'db_table': 'Vente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChefRegionPermission',
            fields=[
                ('id_chef_region', models.OneToOneField(db_column='id_chef_region', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='commercial.chefregion')),
            ],
            options={
                'db_table': 'Chef_Region_Permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommercialPermission',
            fields=[
                ('id_commercial', models.OneToOneField(db_column='id_commercial', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='commercial.commercial')),
            ],
            options={
                'db_table': 'Commercial_Permission',
                'managed': False,
            },
        ),
    ]
