# Generated by Django 6.0.8 on 2026-08-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefregionpermission',
            options={'managed': True},
        ),
    ]
