# Generated by Django 6.0.8 on 2026-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_alter_chefregionpermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialPermissionAgence',
            fields=[
                ('pk', models.CompositePrimaryKey('id_commercial', 'id_agence', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Commercial_Permission_Agence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.CharField(db_collation='French_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_collation='French_CI_AS', max_length=100)),
                ('prenom', models.CharField(blank=True, db_collation='French_CI_AS', max_length=60, null=True)),
                ('email', models.EmailField(db_collation='French_CI_AS', max_length=200, unique=True)),
                ('password', models.CharField(db_collation='French_CI_AS', max_length=255)),
                ('telephone', models.CharField(blank=True, db_collation='French_CI_AS', max_length=30, null=True)),
                ('date_prise_poste', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Utilisateur',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='chefregion',
            options={'managed': False, 'verbose_name': 'Chef région', 'verbose_name_plural': 'Chefs région'},
        ),
        migrations.AlterModelOptions(
            name='chefregionpermission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='commercial',
            options={'managed': False, 'verbose_name': 'Utilisateur commercial', 'verbose_name_plural': 'Commerciaux'},
        ),
    ]
