# Generated by Django 6.0.8 on 2026-09-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_commercialpermissionagence_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_signalement', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('utilisateur', models.ForeignKey(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='commercial.utilisateur')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'db_table': 'Signalement',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
